using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PamelloV7.Framework.Generators;

[Generator]
public class PamelloEventGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<EventClassDescriptor> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 }, 
                transform: GetDescriptor
            )
            .Where(static m => !string.IsNullOrEmpty(m.ClassName));

        context.RegisterSourceOutput(classDeclarations, ExecuteGeneration);
    }

    private static EventClassDescriptor GetDescriptor(GeneratorSyntaxContext context, CancellationToken cancellationToken) {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not INamedTypeSymbol classSymbol) {
            return default;
        }

        var implementsPamelloEvent = InheritsFrom(classSymbol, "IPamelloEvent");
        var implementsRevertible = InheritsFrom(classSymbol, "IRevertiblePamelloEvent");
        
        if (!implementsPamelloEvent && !implementsRevertible) return default;
        
        var baseImplementsPamelloEvent = InheritsFrom(classSymbol.BaseType, "IPamelloEvent");
        var baseImplementsRevertible = InheritsFrom(classSymbol.BaseType, "IRevertiblePamelloEvent");


        var hasInvoker = classSymbol.GetMembers("Invoker").Any();
        var hasRevertPack = classSymbol.GetMembers("RevertPack").Any();
        var hasDefaultPack = false;
        
        if (implementsRevertible) {
            var nestedTypes = classSymbol.GetTypeMembers("Pack");
            
            if (nestedTypes.Length > 0) {
                if (nestedTypes[0] is { IsAbstract: false, Arity: 0 } packType) {
                    hasDefaultPack = packType.Constructors.Any(c => c.Parameters.Length == 0 && !c.IsStatic);
                }
            }
        }

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace 
            ? string.Empty 
            : classSymbol.ContainingNamespace.ToDisplayString();

        return new EventClassDescriptor(
            namespaceName, 
            classSymbol.Name, 
            NeedsInvoker: implementsPamelloEvent && !baseImplementsPamelloEvent && !hasInvoker, 
            NeedsRevertPack: implementsRevertible && !baseImplementsRevertible && !hasRevertPack,
            hasDefaultPack
        );
    }

    private static bool InheritsFrom(INamedTypeSymbol? classSymbol, string targetName) {
        if (classSymbol == null) return false;
        if (classSymbol.AllInterfaces.Any(i => i.Name == targetName)) return true;

        var currentBaseType = classSymbol.BaseType;
        while (currentBaseType != null) {
            if (currentBaseType.Name == targetName) return true;
            currentBaseType = currentBaseType.BaseType;
        }

        return false;
    }

    private static void ExecuteGeneration(SourceProductionContext context, EventClassDescriptor eventClass) {
        if (eventClass is { NeedsInvoker: false, NeedsRevertPack: false }) return;

        var source =
            $$"""
              // <auto-generated/>
              #nullable enable

              using PamelloV7.Framework.Entities;
              using PamelloV7.Framework.Events.RestorePacks.Base;
              using PamelloV7.Framework.Events.Base;
              using PamelloV7.Framework.Containers;
              using System.Text.Json.Serialization;
              
              namespace {{eventClass.Namespace}}
              {
                  partial class {{eventClass.ClassName}}
                  {
                      {{(eventClass.NeedsInvoker ? 
              """
                      public readonly SafeStoredEntity<IPamelloUser> _safeInvoker = new(0);
                      public IPamelloUser? Invoker {
                          get => _safeInvoker.Entity!;
                          set => _safeInvoker.Entity = value;
                      }
              """ : "//invoker is not needed")}}
                      {{(eventClass.NeedsRevertPack ? $"[JsonIgnore] public IRevertPack RevertPack {{ get; set; }}{(
                          eventClass.HasDefaultPack ? " = new Pack();" : " //default pack is not needed"
                      )}" : "//revert pack is not needed")}}
                  }
              }
              """;

        context.AddSource($"{eventClass.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}