using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PamelloV7.Framework.Generators.Extensions;

namespace PamelloV7.Framework.Generators;

[Generator]
public class SafeStoredEntitiesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValuesProvider<SafeStoredEntitiesClassDescriptor> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: GetDescriptor
            ).Where(descriptor => descriptor.EntityInfos.Count > 0);
        
        context.RegisterSourceOutput(classDeclarations, ExecuteGeneration);
    }

    private static SafeStoredEntitiesClassDescriptor GetDescriptor(GeneratorSyntaxContext context, CancellationToken cancellationToken) {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not INamedTypeSymbol classSymbol) {
            return default;
        }

        var entitiesInfos = new List<SafeStoredEntityDescriptor>();

        foreach (var attribute in classSymbol.GetAttributes()) {
            var attributeClass = attribute.AttributeClass;
            if (attributeClass is null || attributeClass.Name != "SafeStoredAttribute") continue;

            var type = attributeClass.TypeArguments.FirstOrDefault();
            if (type is null) continue;
            
            var argument = attribute.ConstructorArguments.FirstOrDefault();
            if (argument.Value is not string propertyName) continue;
            
            entitiesInfos.Add(new SafeStoredEntityDescriptor(type, propertyName));
        }
        
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace 
            ? string.Empty 
            : classSymbol.ContainingNamespace.ToDisplayString();
        
        return new SafeStoredEntitiesClassDescriptor(namespaceName, classSymbol.Name, entitiesInfos);
    }

    private static void ExecuteGeneration(SourceProductionContext context, SafeStoredEntitiesClassDescriptor descriptor) {
        var propertiesSb = new StringBuilder();

        foreach (var propertyInfo in descriptor.EntityInfos) {
            propertiesSb.AppendLine(
                $$"""
                          protected readonly SafeStoredEntity<{{propertyInfo.EntityType.GetFullName()}}> _{{propertyInfo.PropertyName.ToLower()}} = new(0);
                          public {{propertyInfo.EntityType.GetFullName()}} {{propertyInfo.PropertyName}} {
                              get => _{{propertyInfo.PropertyName.ToLower()}}.Entity!;
                              set => _{{propertyInfo.PropertyName.ToLower()}}.Entity = value;
                          }
                  """
            );
        }
        
        var source =
            $$"""
              // <auto-generated/>
              #nullable enable

              using PamelloV7.Framework.Containers;

              namespace {{descriptor.Namespace}}
              {
                  partial class {{descriptor.ClassName}}
                  {
              {{propertiesSb}}
                      // {{descriptor.EntityInfos.Count}} {{(descriptor.EntityInfos.Count == 1 ? "entity" : "entities")}} added
                  }
              }
              """;
        
        context.AddSource($"{descriptor.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
