using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PamelloV7.Framework.Generators.Extensions;

namespace PamelloV7.Framework.Generators;

[Generator]
public class SafeStoredEntitiesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValuesProvider<SafeStoredEntitiesClassDescriptor> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } or RecordDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: GetDescriptor
            ).Where(descriptor => descriptor.SingleEntitiesInfos.Count > 0);
        
        context.RegisterSourceOutput(classDeclarations, ExecuteGeneration);
    }

    private static SafeStoredEntitiesClassDescriptor GetDescriptor(GeneratorSyntaxContext context, CancellationToken cancellationToken) {
        var classDeclaration = context.Node;

        var category = classDeclaration switch {
            ClassDeclarationSyntax => ECategory.Class,
            RecordDeclarationSyntax => ECategory.Record,
            _ => throw new Exception($"Unexpected node type: {classDeclaration.GetType()}")
        };
        
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not INamedTypeSymbol classSymbol) {
            return default;
        }

        var entitiesInfos = new List<SafeStoredEntityDescriptor>();

        var debugOutput = "";

        foreach (var attribute in classSymbol.GetAttributes()) {
            var attributeClass = attribute.AttributeClass;
            if (attributeClass is null || attributeClass.Name != "SafeEntityAttribute") continue;

            var type = attributeClass.TypeArguments.FirstOrDefault();
            if (type is null) continue;
            
            var argument = attribute.ConstructorArguments.FirstOrDefault();
            if (argument.Value is not string propertyName) continue;

            var attributes = attribute.ConstructorArguments.ElementAtOrDefault(1);
            var attributesTypes = attributes.Values.Select(v => v.Value?.ToString()).OfType<string>().ToArray();

            debugOutput += $"Count: {attributesTypes.Length}; {string.Join("; ", attributes.Values.Select(value => value.Value?.GetType()))}";
            
            entitiesInfos.Add(new SafeStoredEntityDescriptor(type, propertyName, attributesTypes));
        }
        
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace 
            ? string.Empty 
            : classSymbol.ContainingNamespace.ToDisplayString();
        
        return new SafeStoredEntitiesClassDescriptor(namespaceName, classSymbol.Name, category, entitiesInfos, debugOutput);
    }

    private static void ExecuteGeneration(SourceProductionContext context, SafeStoredEntitiesClassDescriptor descriptor) {
        var propertiesSb = new StringBuilder();

        foreach (var propertyInfo in descriptor.SingleEntitiesInfos) {
            propertiesSb.AppendLine(
                $$"""
                          public readonly SafeStoredEntity<{{propertyInfo.EntityType.GetFullName()}}> _safe{{propertyInfo.PropertyName}} = new(0);
                          // With {{propertyInfo.PropertyAttributes.Length}} attributes
                          {{string.Join("\n", propertyInfo.PropertyAttributes.Select(attribute => $"[{attribute}]"))}}
                          public {{propertyInfo.EntityType.GetFullName()}}? {{propertyInfo.PropertyName}} {
                              get => _safe{{propertyInfo.PropertyName}}.Entity!;
                              set => _safe{{propertyInfo.PropertyName}}.Entity = value;
                          }
                  """
            );
        }
        
        var source =
            $$"""
              // <auto-generated/>
              #nullable enable

              using PamelloV7.Framework.Containers;

              namespace {{descriptor.Namespace}}
              {
                  partial {{descriptor.Category switch {
                      ECategory.Class => "class",
                      ECategory.Record => "record",
                      _ => throw new Exception($"Unexpected category: {descriptor.Category}")
                  }}} {{descriptor.ClassName}}
                  {
              {{propertiesSb}}
                      // {{descriptor.SingleEntitiesInfos.Count}} {{(descriptor.SingleEntitiesInfos.Count == 1 ? "entity" : "entities")}} added
                  }
              }
              
              //debug: {{descriptor.DebugOutput}}
              """;
        
        context.AddSource($"{descriptor.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
