name: Build and publish NuGet packages
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Matches your target frameworks

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore PamelloV7.sln

      # Build PamelloV7.Core
      - name: Build PamelloV7.Core
        run: dotnet build PamelloV7.Core/PamelloV7.Core.csproj --configuration Release

      # Build PamelloV7.Wrapper
      - name: Build PamelloV7.Wrapper
        run: dotnet build PamelloV7.Wrapper/PamelloV7.Wrapper.csproj --configuration Release

      # Pack PamelloV7.Core
      - name: Pack PamelloV7.Core
        run: dotnet pack PamelloV7.Core/PamelloV7.Core.csproj --configuration Release --output nupkgs

      # Pack PamelloV7.Wrapper
      - name: Pack PamelloV7.Wrapper
        run: dotnet pack PamelloV7.Wrapper/PamelloV7.Wrapper.csproj --configuration Release --output nupkgs

      # Push to NuGet.org
      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for pkg in nupkgs/*.nupkg; do
            dotnet nuget push "$pkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
          done
        shell: bash
